spring:
  application:
    name: boasaude
  servlet:
    multipart:
      max-file-size: 1MB      # Tamanho máximo por arquivo
      max-request-size: 5MB   # Tamanho máximo da requisição
      enabled: true            # Habilita multipart

  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuração de armazenamento de arquivos
storage:
  path: uploads/images         # Pasta padrão para imagens


jwt:
  secret: ${JWT_SECRET}
